version: '3'

volumes:
  wordpress-mysql:
    driver: "local"


services:


  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - wordpress-mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

  adminer:
    image: adminer
    links:
      - mysql:db
    ports:
      - 9000:8080


  bedrock_sage_lara:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/wordpress
      - ./:/tmp/setup
    environment:
      BEDROCK_PATH: ${BEDROCK_PATH}
      LARAVEL_PATH: ${LARAVEL_PATH}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mysql
      WP_ENV: development
      WP_SITEURL: http://127.0.0.1:${APACHE_PORT}/wp
      WP_INIT: ${WP_INIT} # set WP_INIT to yes to initialize new project
      SITE_TITLE: Wordpress
      ADMIN_USER: admin
      ADMIN_PASS: password
      ADMIN_EMAIL: test@test.com
      WP_HOME: http://127.0.0.1:${APACHE_PORT}

  #this container will be used only in the dev environment when using sage theme. 
  #it will run server using webpack that watch resources file changes and compile them
  sage_builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: /opt/wait.sh
    command: yarn --cwd=${BEDROCK_PATH}/web/app/themes/sage run start
    depends_on:
      - bedrock_sage_lara
    volumes:
      - ${PROJECT_PATH}:/var/www/wordpress
    links:
      - bedrock_sage_lara:bedrock_sage_lara
    environment:
      APACHE_CONTAINER_PORT: 80

  #this container will be used only in the dev environment when using laravel theme. 
  #it will run server using webpack that watch resources file changes and compile them
  laravel_builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: /opt/wait.sh
    command: npm --prefix ${LARAVEL_PATH} run watch
    depends_on:
      - bedrock_sage_lara
    volumes:
      - ${PROJECT_PATH}:/var/www/wordpress
    links:
      - bedrock_sage_lara:bedrock_sage_lara
    environment:
      APACHE_CONTAINER_PORT: 80


