# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false


  config.vm.define "dokku" do |dokku|
    dokku.vm.box = "ubuntu/xenial64"
    dokku.vm.hostname = "dokku"
    dokku.vm.network "private_network", ip: "192.168.101.10"

    dokku.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    dokku.vm.synced_folder ".", "/vagrant", disabled: true
    dokku.vm.provision "shell", inline: <<-SHELL
      DOMAIN="dokku.local"
      DOKKU_PUB_KEY_PATH="/home/vagrant/.ssh/authorized_keys"
      APP_NAME="wordpress"

      echo "Installing Dokku"
      # wget https://raw.githubusercontent.com/dokku/dokku/v0.11.3/bootstrap.sh;
      # DOKKU_TAG=v0.11.3 bash bootstrap.sh

      dokku ssh-keys:add admin $DOKKU_PUB_KEY_PATH < /dev/null #This command is behaving and try to fetch sshkey from stdin, < /dev/null fix that

      hostname $DOMAIN
      grep /etc/hosts -qe "^127.0.0.1 $DOMAIN$" || echo "127.0.0.1 $DOMAIN" | tee -a /etc/hosts
      echo "$DOMAIN" > /etc/hostname
      dokku domains:set-global $DOMAIN

      echo "Killing dokku ui installer server"
      DUKKU_INSTALLER_SERVER_PID=$(netstat -ntulp | grep "0.0.0.0:2000" | awk '{print $7}' | awk -F '/' '{printf $1}')
      if [ -n "$DUKKU_INSTALLER_SERVER_PID" ]
      then
        kill -9 $DUKKU_INSTALLER_SERVER_PID
      fi

      
      echo "Installing MySQL Dokku plugin"
      dokku plugin:list | tail -n '+2' | awk '{print $1}' | grep -qe ^mysql$
      if [ $? -eq 0 ]
      then
          echo "MySQL plugin is already installed"
      else
          echo "Installing MySQL plugin..."
          dokku plugin:install https://github.com/dokku/dokku-mysql.git mysql
      fi
      
      echo "Creating wordpress app"
      dokku apps:create $APP_NAME
      dokku domains:enable $APP_NAME
    SHELL
  end


end

